---

- name: file █ Ensure old netplan configuration is erased
  ansible.builtin.file:
    path: /etc/netplan/00-installer-config.yaml
    state: absent
  tags:
    - identify

- name: file █ Disable netplan management
  ansible.builtin.copy:
    src: 01-netcfg.yaml
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0644
  notify:
    - command █ netplan generate
  tags:
    - identify

- name: template █ Render networkd NICs configuration
  ansible.builtin.template:
    src: networkd.j2
    dest: "/etc/systemd/network/{{ item.conn_name | default(item.interface) | string }}.network"
    owner: root
    group: root
    mode: 0644
  loop: "{{ network_interfaces }}"
  notify:
    - command █ networkctl reload
  tags:
    - template
    - identify

- name: template █ Render networkd netdevs configuration
  ansible.builtin.template:
    src: "{{ item.type }}.netdev.j2"
    dest: "/etc/systemd/network/{{ item.conn_name | default(item.interface) | string }}.netdev"
    owner: root
    group: root
    mode: 0644
  loop: "{{ network_interfaces }}"
  when: item.type is defined and item.type in ["bond", "vlan"]
  notify:
    - command █ networkctl reload
  tags:
    - template
    - identify

- name: include_tasks ░ Use dedicated task for VLANs
  ansible.builtin.include_tasks: vlan.yml
  when: "'vlan' in (network_interfaces | map(attribute='type') | reject('undefined') | list)"
  tags:
    - internal

- name: meta █ Run handlers
  ansible.builtin.meta: flush_handlers
